language: android
jdk:
  - oraclejdk8
  - openjdk8
env:
  global:
    - ANDROID_TARGET=android-28
    - BUILD_TOOLS=28.0.3
android:
  components:
  - tools
  - platform-tools
  - build-tools-$BUILD_TOOLS
  - extra-android-m2repository
  - $ANDROID_TARGET
before_install:
  - chmod +x gradlew
script:
  - ./gradlew build

